const labels: Record<string, string> = {
  name: "Nazwa",
  "Loop music selection": "Zapętl zaznaczony fragment muzyki",
  "Scene / camera": "Scena / kamera",
  "shutter cuts": "Cięcia migawkowe",
  "panorama expansion": "Rozwinięcie kadru",
  "monitor cascade / interruptions": "Kaskada monitorów / przerwania",
  "Drag playhead": "Przesuń głowicę",
  "Drag IN point": "Przesuń punkt IN",
  "Drag OUT point": "Przesuń punkt OUT",
  "Drag playhead · Shift-drag creates a range":
    "Przesuń głowicę · Shift + przeciągnięcie zaznacza zakres",
  "Drag IN": "Przesuń IN",
  "Drag OUT": "Przesuń OUT",
  "intro / reveal": "wejście / odsłonięcie",
  payoff: "kulminacja",
  restraint: "wyczekiwanie",
  "rhythmic response": "reakcja w rytmie",
  "Resize Scene Tree": "Zmień szerokość warstw",
  "Resize Inspector": "Zmień szerokość inspektora",
  "Resize Timeline": "Zmień wysokość osi czasu",
  "Go to cue": "Przejdź do punktu",
  "Loop around cue": "Zapętl okolicę punktu",
  "Set IN here": "Ustaw IN tutaj",
  "Set OUT here": "Ustaw OUT tutaj",
  "Copy timestamp": "Kopiuj czas",
  Typography: "Typografia",
  "Cash fountain": "Fontanna gotówki",
  "Cash handoff": "Przekazanie gotówki",
  "Cash storm": "Burza gotówki",
  cash: "gotówka",
  intro: "wejście",
  build: "narastanie",
  release: "wyciszenie",
  settle: "uspokojenie",
  firstImpact: "pierwszy akcent",
  donorReveal: "odsłonięcie nazwy",
  buildStart: "początek narastania",
  preDrop: "przed kulminacją",
  heroDrop: "kulminacja",
  outroStart: "początek zakończenia",
  informationStart: "początek informacji",
  "source loop": "pętla źródła",
  ALERT: "ALERT",
  BEAT: "UDERZENIE",
  BAR: "TAKT",
  MEDIA: "MEDIA",
  HOLD: "ZATRZYMANIE",
  LOOP: "PĘTLA",
  "VOCAL ≈": "WOKAL ≈",
  "HERO ENDED": "KONIEC ANIMACJI",
  "LIFECYCLE +": "PRZEBIEG +",
  PLAYING: "ODTWARZANIE",
  "Original PCM waveform": "Przebieg oryginalnego PCM",
  "Original music min/max waveform": "Przebieg min/max oryginalnej muzyki",
  "Information remains visible across all speech and the reading gate":
    "Informacja pozostaje widoczna podczas czytania i do końca czasu na przeczytanie.",
  "Choose a local PNG, JPEG or WebP smaller than 2 MB":
    "Wybierz lokalny PNG, JPEG lub WebP mniejszy niż 2 MB.",

  "Turkey two-step": "Turecki dwukrok",
  "Masked dance floor": "Taniec w masce",
  "Rodent rave": "Gryzoniowy rave",
  "Deadpan paper roll": "Suchy żart i paragon",
  "Webcam overload": "Pikselowy chaos",
  "Say my name · shared Donate7 track": "Say my name · wspólny utwór Donate7",
  "TTS ·": "Czytanie ·",
  "Source media · frame / hold": "Media · klatka / zatrzymanie",
  "Media · loop / hold": "Media · pętla / zatrzymanie",
  "Cash waves": "Fale gotówki",
  "Space play/pause · Home start · ← → 10 ms · Shift ← → 50 ms · ↑ ↓ cues":
    "Spacja odtwórz/pauza · Home początek · ← → 10 ms · Shift ← → 50 ms · ↑ ↓ punkty",
  "Original audio clock · local authoring only": "Zegar oryginalnej muzyki · lokalne Studio",
  "Seek −50 ms (Shift+←)": "Cofnij o 50 ms (Shift+←)",
  "Seek +50 ms (Shift+→)": "Przesuń o 50 ms (Shift+→)",
  "resume from pose → loop": "Wznowienie od pozy → pętla",
  ready: "Gotowe",
  loading: "Wczytywanie",
  "gif-fallback": "Zapasowy GIF",
  auto: "AUTO",
  high: "HIGH",
  medium: "MEDIUM",
  safe: "SAFE",

  "Scene tree": "Warstwy sceny",
  "Program · 1920 × 1080": "Podgląd · 1920 × 1080",
  Properties: "Właściwości",
  Timeline: "Oś czasu",
  "Source media": "Media źródłowe",
  "Scene forms": "Elementy sceny",
  Callouts: "Hasła / reakcje",
  Name: "Nazwa",
  Amount: "Kwota",
  Information: "Informacja",
  Cash: "Gotówka",
  Scene: "Scena",
  "Hero Only": "Tylko animacja",
  "Hero only": "Tylko animacja",
  "HERO ONLY": "TYLKO ANIMACJA",
  "Full Alert": "Pełny alert",
  "FULL ALERT": "PEŁNY ALERT",
  "Full donation": "Pełny alert",
  View: "Widok",
  Fit: "Dopasuj",
  Center: "Wyśrodkuj",
  "Stream preview": "Podgląd streama",
  "Stream Preview": "Podgląd streama",
  Background: "Tło",
  checker: "Szachownica",
  solid: "Ciemne",
  transparent: "Przezroczyste",
  none: "Brak",
  "Donation data": "Dane donate’a",
  Inspector: "Inspektor",
  Export: "Eksport",
  Nickname: "Nazwa",
  "Amount · PLN": "Kwota · PLN",
  "Amount PLN": "Kwota PLN",
  Message: "Wiadomość",
  "Commission · PLN": "Prowizja · PLN",
  "Commission PLN": "Prowizja PLN",
  "Test viewer content in this scene.": "Sprawdź dane widza w tej scenie.",
  "Enter PLN with up to two decimal places.":
    "Wpisz PLN z maksymalnie dwiema cyframi po przecinku.",
  "Resolve tier from amount": "Dobierz scenę z kwoty",
  threshold: "Próg",
  "Detail budget": "Poziom szczegółów",
  "Replay seed": "Ziarno losowania",
  "Visibility overrides are local to Studio.": "Widoczność warstw zmieniasz tylko w Studio.",
  "Local test voice · Paulina": "Lokalny głos testowy · Paulina",
  "Fixed spoken samples exercise enabled TTS stages. Custom data appears on the information card.":
    "Stałe próbki sprawdzają etapy czytania. Własne dane pojawiają się na karcie informacji.",
  Fixture: "Próbka",
  Duration: "Czas trwania",
  Volume: "Głośność",
  Voice: "Głos",
  Sample: "Treść próbki",
  State: "Stan",
  "Playing local fixture": "Odtwarzanie próbki",
  "Normal · local fixture": "Gotowa próbka lokalna",
  "Failed · no fallback substituted": "Błąd odtwarzania próbki",
  "Preview this TTS": "Posłuchaj próbki",
  "Vocal timing": "Czas wokalu",
  "Selected cue": "Wybrany punkt",
  Source: "Źródło",
  "Media position": "Pozycja mediów",
  "Pose hold": "Zatrzymana poza",
  "Echo delay": "Opóźnienie kopii",
  "Tempo estimate": "Szacowane tempo",
  "Detail tier": "Poziom szczegółów",
  "Cash cue": "Punkt gotówki",
  "No active cash wave": "Brak aktywnej fali gotówki",
  "No live echoes": "Brak animowanych kopii",
  None: "Brak",
  "Measured activity": "Zmierzona aktywność",
  "Visual sync offset · ms": "Korekta synchronizacji · ms",
  "Schedule click + flash": "Zaplanuj klik i błysk",
  "Approve downbeat at playhead": "Zatwierdź początek taktu tutaj",
  Approved: "Zatwierdzono",
  "Inference · needs review": "Kandydat · do sprawdzenia",
  "Word / phrase": "Słowo / fraza",
  Start: "Początek",
  End: "Koniec",
  "Approve correction": "Zatwierdź korektę",
  "Use as vocal reaction cue": "Użyj jako punkt reakcji wokalnej",
  "Save authored corrections": "Zapisz korekty",
  "Select a word or phrase in the timeline to review its timing. Automatic words and downbeats are candidates.":
    "Wybierz słowo lub frazę na osi czasu. Automatyczne słowa i początki taktów wymagają zatwierdzenia.",
  "Render export": "Renderowanie eksportu",
  "Deterministic frames · local worker": "Powtarzalne klatki · lokalny proces",
  Range: "Zakres",
  "Current selection": "Bieżące zaznaczenie",
  "Cue neighborhood": "Okolica punktu",
  Resolution: "Rozdzielczość",
  Format: "Format",
  "Solid graphite": "Ciemne tło",
  "Transparent · WebM": "Przezroczystość · WebM",
  "Original music + full alert test TTS": "Oryginalna muzyka + testowe czytanie pełnego alertu",
  Seed: "Ziarno",
  Quality: "Szczegóły",
  Selection: "Zaznaczenie",
  "Render Export": "Renderuj eksport",
  idle: "Gotowy do eksportu",
  starting: "Przygotowanie",
  rendering: "Renderowanie",
  encoding: "Kodowanie",
  complete: "Zakończono",
  failed: "Błąd",
  "Loading music…": "Wczytywanie muzyki…",
  Ready: "Gotowe",
  "Previous cue": "Poprzedni punkt",
  "Next cue": "Następny punkt",
  Pause: "Pauza",
  Play: "Odtwórz",
  Restart: "Od początku",
  "Toggle Scene Tree": "Pokaż / ukryj warstwy",
  "Toggle Inspector": "Pokaż / ukryj inspektor",
  "Restore workspace": "Przywróć układ",
  "Maximize active panel": "Powiększ aktywny panel",
  "Reset Workspace": "Przywróć domyślny układ",
  "Center viewer": "Wyśrodkuj podgląd",
  "Custom stream frame": "Własne tło streama",
  "Custom stream image": "Własny obraz streama",
  "Viewer zoom": "Powiększenie podglądu",
  "Stage background": "Tło podglądu",
  "Program monitor": "Podgląd sceny",
  "Waveform overlay": "Warstwa przebiegu",
  "Timeline zoom": "Powiększenie osi czasu",
  "Timeline snapping": "Przyciąganie osi czasu",
  "Multitrack timeline": "Wielotorowa oś czasu",
  "Music time": "Czas muzyki",
  "Export range": "Zakres eksportu",
  Overlay: "Warstwa",
  Zoom: "Powiększenie",
  "Center playhead": "Wyśrodkuj głowicę",
  Snap: "Przyciąganie",
  Off: "Wyłączone",
  "Beat (estimate)": "Uderzenie (szacunek)",
  "Downbeat (estimate)": "Początek taktu (szacunek)",
  Cue: "Punkt animacji",
  "Source frame": "Klatka źródłowa",
  "Loop selection": "Zapętl zaznaczenie",
  "Clear loop": "Usuń pętlę",
  "Restore hidden tracks": "Przywróć ukryte ścieżki",
  "Hide track": "Ukryj ścieżkę",
  "Fit track height": "Dopasuj wysokość ścieżki",
  "Go to first event": "Pierwsze zdarzenie",
  "Go to start": "Przejdź na początek",
  "Set IN": "Ustaw IN",
  "Set OUT": "Ustaw OUT",
  TIME: "CZAS",
  "Lifecycle / Hero": "Przebieg / Animacja",
  "Hero / original music": "Animacja / oryginalna muzyka",
  COMPLETE: "KONIEC",
  "Information · overlaps speech": "Informacja · podczas czytania",
  Outro: "Zakończenie",
  Out: "Koniec",
  "Music · waveform": "Muzyka · przebieg",
  "Beats · estimated": "Uderzenia · szacunek",
  "Downbeats / bars": "Początki taktów",
  "Vocal reactions": "Reakcje wokalne · energia",
  "Structure · authored": "Struktura · zatwierdzona",
  "Vocal phrases": "Frazy ASR · niezatwierdzone",
  "Vocal words": "Rozpoznane słowa",
  "Authored cues": "Punkty animacji",
  "Source media · loop / hold": "Media · pętla / zatrzymanie",
  "Cash · directed waves": "Gotówka · fale",
  "TTS · Nickname": "Czytanie · Nazwa",
  "TTS · Amount": "Czytanie · Kwota",
  "TTS · Message": "Czytanie · Wiadomość",
  nickname: "Nazwa",
  amount: "Kwota",
  message: "Wiadomość",
  hero: "Animacja",
  information: "Informacja",
  "tts-nickname": "Czytanie nazwy",
  "tts-amount": "Czytanie kwoty",
  "tts-message": "Czytanie wiadomości",
  outro: "Zakończenie",
  loudness: "Głośność",
  bass: "Bas",
  vocals: "Wokal",
  drums: "Perkusja",
  "Motion Studio requires a desktop-sized viewport.":
    "Motion Studio wymaga dużego okna przeglądarki.",
  "Current viewport:": "Rozmiar okna:",
  "Recommended minimum:": "Zalecane minimum:",
  "Use a desktop or laptop and enlarge the browser window.":
    "Powiększ okno na komputerze lub laptopie.",
  "Arms-wide ovation": "Owacja z otwartymi ramionami",
  "Heart from the booth": "Serce z kabiny",
  "Pixel monitor overload": "Pikselowy chaos",
  "Turkish two-step": "Turecki dwukrok",
  "Masked dance chorus": "Taniec w masce",
  "Rodent projector": "Projektor reakcji",
  "Deadpan paper unroll": "Suchy żart i paragon",
};
export const pl = (value: string) => labels[value] ?? value;
